baseURL = "https://distinctlypr.co"
languageCode = "en-GB"
title = "Distinctly PR"
theme = "distinctlypr-v1"

[params]
    copyright1 = "&copy; Copyright [year] Distinctly Digital Limited. Registered Company No. 06905971"
    copyright2 = "Registered Address: Little Sharlowes, Flaunden, Hertfordshire, HP3 0PP."
