baseURL = "/"
languageCode = "en-GB"
title = "Distinctly PR"

[params]
    copyright = "&copy; Copyright [year] Distinctly Digital Limited. Registered Company No. 06905971"
    phone = "01923 728191"
    email = "info@distinctlypr.co"