baseURL = "https://distinctlypr.netlify.com"
languageCode = "en-GB"
title = "Distinctly PR"

[params]
    copyright1 = "&copy; Copyright [year] Distinctly Digital Limited. Registered Company No. 06905971"
    copyright2 = "Registered Address: Little Sharlowes, Flaunden, Hertfordshire, HP3 0PP."
    phone = "01923 728191"
    email = "info@distinctlypr.co"