[build]
    command = "hugo"
    publish = "public"

[context.production]
    [context.production.environment]
        HUGO_ENV = "production"
        NODE_ENV = "production"
        HUGO_VERSION = "0.78.1"