name = "Distinctly PR"
description = "A bespoke theme for Distinctly PR"
homepage = ""
tags = []
features = []
min_version = "0.25.1"

[author]
  name = "Indigo Tree"
  homepage = "https://indigotree.co.uk"
