backend:
  name: github
  repo: indigotree/distinctly-pr-hugo
  branch: master
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: 'page'
    label: "Page"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Hero Image (width 1750px)", name: "hero_image_1750", widget: "image", required: false }
      - { label: "Hero Image (width 1050px)", name: "hero_image_1050", widget: "image", required: false }
      - { label: "Hero Image (width 320px)", name: "hero_image_320", widget: "image", required: false }
      - { label: "Hero Heading", name: "hero_heading", widget: "string", required: false }
      - { label: "Hero Subheading", name: "hero_subheading", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "SEO Title", name: "seo_title", widget: "string", required: false }
      - { label: "SEO Description", name: "description", widget: "string", required: false }